# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhizome < Formula
  desc ""
  homepage "https://github.com/atomicobject/rhizome"
  version "0.27.0"

  on_macos do
    url "https://github.com/atomicobject/rhizome/releases/download/v0.27.0/rhizome_0.27.0_darwin_all.tar.gz"
    sha256 "c8bfd443aef81f89f16ec3e4c41c710c2c2d473ade87e299b267746aac84ba95"

    def install
      bin.install "rhizome"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomicobject/rhizome/releases/download/v0.27.0/rhizome_0.27.0_linux_amd64.tar.gz"
      sha256 "f9d3ea003f5b6934360491a6c31a1da2acf376802aab741f7ed36df48937d13d"
      def install
        bin.install "rzm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomicobject/rhizome/releases/download/v0.27.0/rhizome_0.27.0_linux_arm64.tar.gz"
      sha256 "753c538a0cfd8f87519b2aa90f2e9cf39aaa4814ca64710e29898e38e136d6d3"
      def install
        bin.install "rzm"
      end
    end
  end
end
