# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhizome < Formula
  desc ""
  homepage "https://github.com/atomicobject/rhizome"
  version "0.22.0"

  on_macos do
    url "https://github.com/atomicobject/rhizome/releases/download/v0.22.0/rhizome_0.22.0_darwin_all.tar.gz"
    sha256 "12c0da5d095e689c21a05432ec1980b7ff6ad6cb18fcfc3bcd8848e92bb4d26b"

    def install
      bin.install "rhizome"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomicobject/rhizome/releases/download/v0.22.0/rhizome_0.22.0_linux_amd64.tar.gz"
      sha256 "9cd20b351d8d4c77238037af56b9fa4c7c984b2650449a74183a61de255028b1"
      def install
        bin.install "rzm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atomicobject/rhizome/releases/download/v0.22.0/rhizome_0.22.0_linux_arm64.tar.gz"
      sha256 "7102bc6d26ed23d4821a38be3f081ced9def265411841407c7b6ca65ad3747cc"
      def install
        bin.install "rzm"
      end
    end
  end
end
